--Insert country data

INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Afghanistan','93','AF / AFG');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Albania','355','AL / ALB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Algeria','213','DZ / DZA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('American Samoa','1-684','AS / ASM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Andorra','376','AD / AND');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Angola','244','AO / AGO');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Anguilla','1-264','AI / AIA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Antarctica','672','AQ / ATA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Antigua and Barbuda','1-268','AG / ATG');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Argentina','54','AR / ARG');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Armenia','374','AM / ARM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Aruba','297','AW / ABW');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Australia','61','AU / AUS');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Austria','43','AT / AUT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Azerbaijan','994','AZ / AZE');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Bahamas','1-242','BS / BHS');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Bahrain','973','BH / BHR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Bangladesh','880','BD / BGD');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Barbados','1-246','BB / BRB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Belarus','375','BY / BLR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Belgium','32','BE / BEL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Belize','501','BZ / BLZ');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Benin','229','BJ / BEN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Bermuda','1-441','BM / BMU');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Bhutan','975','BT / BTN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Bolivia','591','BO / BOL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Bosnia and Herzegovina','387','BA / BIH');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Botswana','267','BW / BWA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Brazil','55','BR / BRA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('British Indian Ocean Territory','246','IO / IOT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('British Virgin Islands','1-284','VG / VGB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Brunei','673','BN / BRN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Bulgaria','359','BG / BGR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Burkina Faso','226','BF / BFA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Burundi','257','BI / BDI');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Cambodia','855','KH / KHM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Cameroon','237','CM / CMR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Canada','1','CA / CAN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Cape Verde','238','CV / CPV');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Cayman Islands','1-345','KY / CYM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Central African Republic','236','CF / CAF');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Chad','235','TD / TCD');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Chile','56','CL / CHL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('China','86','CN / CHN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Christmas Island','61','CX / CXR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Cocos Islands','61','CC / CCK');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Colombia','57','CO / COL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Comoros','269','KM / COM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Cook Islands','682','CK / COK');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Costa Rica','506','CR / CRI');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Croatia','385','HR / HRV');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Cuba','53','CU / CUB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Curacao','599','CW / CUW');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Cyprus','357','CY / CYP');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Czech Republic','420','CZ / CZE');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Democratic Republic of the Congo','243','CD / COD');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Denmark','45','DK / DNK');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Djibouti','253','DJ / DJI');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Dominica','1-767','DM / DMA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Dominican Republic','1-809, 1-829, 1-849','DO / DOM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('East Timor','670','TL / TLS');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Ecuador','593','EC / ECU');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Egypt','20','EG / EGY');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('El Salvador','503','SV / SLV');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Equatorial Guinea','240','GQ / GNQ');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Eritrea','291','ER / ERI');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Estonia','372','EE / EST');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Ethiopia','251','ET / ETH');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Falkland Islands','500','FK / FLK');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Faroe Islands','298','FO / FRO');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Fiji','679','FJ / FJI');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Finland','358','FI / FIN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('France','33','FR / FRA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('French Polynesia','689','PF / PYF');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Gabon','241','GA / GAB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Gambia','220','GM / GMB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Georgia','995','GE / GEO');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Germany','49','DE / DEU');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Ghana','233','GH / GHA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Gibraltar','350','GI / GIB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Greece','30','GR / GRC');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Greenland','299','GL / GRL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Grenada','1-473','GD / GRD');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Guam','1-671','GU / GUM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Guatemala','502','GT / GTM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Guernsey','44-1481','GG / GGY');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Guinea','224','GN / GIN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Guinea-Bissau','245','GW / GNB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Guyana','592','GY / GUY');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Haiti','509','HT / HTI');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Honduras','504','HN / HND');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Hong Kong','852','HK / HKG');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Hungary','36','HU / HUN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Iceland','354','IS / ISL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('India','91','IN / IND');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Indonesia','62','ID / IDN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Iran','98','IR / IRN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Iraq','964','IQ / IRQ');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Ireland','353','IE / IRL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Isle of Man','44-1624','IM / IMN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Israel','972','IL / ISR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Italy','39','IT / ITA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Ivory Coast','225','CI / CIV');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Jamaica','1-876','JM / JAM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Japan','81','JP / JPN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Jersey','44-1534','JE / JEY');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Jordan','962','JO / JOR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Kazakhstan','7','KZ / KAZ');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Kenya','254','KE / KEN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Kiribati','686','KI / KIR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Kosovo','383','XK / XKX');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Kuwait','965','KW / KWT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Kyrgyzstan','996','KG / KGZ');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Laos','856','LA / LAO');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Latvia','371','LV / LVA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Lebanon','961','LB / LBN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Lesotho','266','LS / LSO');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Liberia','231','LR / LBR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Libya','218','LY / LBY');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Liechtenstein','423','LI / LIE');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Lithuania','370','LT / LTU');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Luxembourg','352','LU / LUX');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Macau','853','MO / MAC');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Macedonia','389','MK / MKD');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Madagascar','261','MG / MDG');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Malawi','265','MW / MWI');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Malaysia','60','MY / MYS');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Maldives','960','MV / MDV');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Mali','223','ML / MLI');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Malta','356','MT / MLT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Marshall Islands','692','MH / MHL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Mauritania','222','MR / MRT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Mauritius','230','MU / MUS');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Mayotte','262','YT / MYT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Mexico','52','MX / MEX');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Micronesia','691','FM / FSM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Moldova','373','MD / MDA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Monaco','377','MC / MCO');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Mongolia','976','MN / MNG');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Montenegro','382','ME / MNE');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Montserrat','1-664','MS / MSR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Morocco','212','MA / MAR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Mozambique','258','MZ / MOZ');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Myanmar','95','MM / MMR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Namibia','264','NA / NAM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Nauru','674','NR / NRU');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Nepal','977','NP / NPL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Netherlands','31','NL / NLD');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Netherlands Antilles','599','AN / ANT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('New Caledonia','687','NC / NCL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('New Zealand','64','NZ / NZL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Nicaragua','505','NI / NIC');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Niger','227','NE / NER');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Nigeria','234','NG / NGA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Niue','683','NU / NIU');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('North Korea','850','KP / PRK');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Northern Mariana Islands','1-670','MP / MNP');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Norway','47','NO / NOR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Oman','968','OM / OMN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Pakistan','92','PK / PAK');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Palau','680','PW / PLW');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Palestine','970','PS / PSE');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Panama','507','PA / PAN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Papua New Guinea','675','PG / PNG');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Paraguay','595','PY / PRY');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Peru','51','PE / PER');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Philippines','63','PH / PHL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Pitcairn','64','PN / PCN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Poland','48','PL / POL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Portugal','351','PT / PRT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Puerto Rico','1-787, 1-939','PR / PRI');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Qatar','974','QA / QAT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Republic of the Congo','242','CG / COG');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Reunion','262','RE / REU');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Romania','40','RO / ROU');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Russia','7','RU / RUS');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Rwanda','250','RW / RWA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Saint Barthelemy','590','BL / BLM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Saint Helena','290','SH / SHN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Saint Kitts and Nevis','1-869','KN / KNA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Saint Lucia','1-758','LC / LCA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Saint Martin','590','MF / MAF');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Saint Pierre and Miquelon','508','PM / SPM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Saint Vincent and the Grenadines','1-784','VC / VCT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Samoa','685','WS / WSM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('San Marino','378','SM / SMR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Sao Tome and Principe','239','ST / STP');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Saudi Arabia','966','SA / SAU');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Senegal','221','SN / SEN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Serbia','381','RS / SRB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Seychelles','248','SC / SYC');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Sierra Leone','232','SL / SLE');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Singapore','65','SG / SGP');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Sint Maarten','1-721','SX / SXM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Slovakia','421','SK / SVK');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Slovenia','386','SI / SVN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Solomon Islands','677','SB / SLB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Somalia','252','SO / SOM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('South Africa','27','ZA / ZAF');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('South Korea','82','KR / KOR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('South Sudan','211','SS / SSD');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Spain','34','ES / ESP');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Sri Lanka','94','LK / LKA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Sudan','249','SD / SDN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Suriname','597','SR / SUR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Svalbard and Jan Mayen','47','SJ / SJM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Swaziland','268','SZ / SWZ');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Sweden','46','SE / SWE');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Switzerland','41','CH / CHE');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Syria','963','SY / SYR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Taiwan','886','TW / TWN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Tajikistan','992','TJ / TJK');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Tanzania','255','TZ / TZA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Thailand','66','TH / THA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Togo','228','TG / TGO');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Tokelau','690','TK / TKL');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Tonga','676','TO / TON');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Trinidad and Tobago','1-868','TT / TTO');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Tunisia','216','TN / TUN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Turkey','90','TR / TUR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Turkmenistan','993','TM / TKM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Turks and Caicos Islands','1-649','TC / TCA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Tuvalu','688','TV / TUV');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('U.S. Virgin Islands','1-340','VI / VIR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Uganda','256','UG / UGA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Ukraine','380','UA / UKR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('United Arab Emirates','971','AE / ARE');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('United Kingdom','44','GB / GBR');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('United States','1','US / USA');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Uruguay','598','UY / URY');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Uzbekistan','998','UZ / UZB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Vanuatu','678','VU / VUT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Vatican','379','VA / VAT');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Venezuela','58','VE / VEN');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Vietnam','84','VN / VNM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Wallis and Futuna','681','WF / WLF');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Western Sahara','212','EH / ESH');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Yemen','967','YE / YEM');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Zambia','260','ZM / ZMB');
INSERT INTO country(countryName,phonePrefix,isoCodes) VALUES ('Zimbabwe','263','ZW / ZWE');


--Insert data for data format
INSERT INTO dataFormat(format) VALUES ('txt');
INSERT INTO dataFormat(format) VALUES ('json');
INSERT INTO dataFormat(format) VALUES ('pdf');
INSERT INTO dataFormat(format) VALUES ('java');
INSERT INTO dataFormat(format) VALUES ('xml');
INSERT INTO dataFormat(format) VALUES ('doc');
INSERT INTO dataFormat(format) VALUES ('docx');
INSERT INTO dataFormat(format) VALUES ('xls');
INSERT INTO dataFormat(format) VALUES ('xlsb');
INSERT INTO dataFormat(format) VALUES ('xlsm');
INSERT INTO dataFormat(format) VALUES ('xlsx');


--Insert data for temperature units
INSERT INTO temperatureUnit(unitCode,unitName,unitDescription) VALUES ('C','Celcius','Celcius degree');
INSERT INTO temperatureUnit(unitCode,unitName,unitDescription) VALUES ('f','Fahrenheit','fahrenheit degree');
INSERT INTO temperatureUnit(unitCode,unitName,unitDescription) VALUES ('K','Kelvin','Kelvin degree');



--Insert data for pressure units
INSERT INTO pressureUnit(unitCode,unitName,unitDescription) VALUES ('Pa','Pascal','Pascal unit');
INSERT INTO pressureUnit(unitCode,unitName,unitDescription) VALUES ('bar','Bar','Bar unit');
INSERT INTO pressureUnit(unitCode,unitName,unitDescription) VALUES ('at','Technical atmosphere','Technical atmosphere unit');
INSERT INTO pressureUnit(unitCode,unitName,unitDescription) VALUES ('atm','Standard atmosphere','Standard atmosphere unit');
INSERT INTO pressureUnit(unitCode,unitName,unitDescription) VALUES ('Torr','Torr','Torr unit');
INSERT INTO pressureUnit(unitCode,unitName,unitDescription) VALUES ('lbf/in2','Pounds per square inch','Pounds per square inch unit');

--Insert data for nasa-power identifiers
INSERT INTO nasaPowerIdentifier(identifier) VALUES('SinglePoint');
INSERT INTO nasaPowerIdentifier(identifier) VALUES('Regional');
INSERT INTO nasaPowerIdentifier(identifier) VALUES('Global');

--Insert test users
insert into users(id, firstName, lastName, password, email, gender, birthday, birthplace, country, rights, createdDate, updatedDate) values  (1,'jon','doe','password','jondoe@gmail.com','M','1990-09-01','Berlin,Germany','Germany','USER','1990-09-01','1990-09-01' );
insert into users(id, firstName, lastName, password, email, gender, birthday, birthplace, country, rights, createdDate, updatedDate) values  (2,'jane','doe','password','janedoe@gmail.com','M','1990-09-01','Paris,France','France','USER','1990-09-01','1990-09-01' );



