name: extract-service

jobManager:
  threadPoolSize: 2
  jobs:
    - name: nasa-job
      sleep: 2000
      failedAttemptMax: 5
      apiProvider:
        name: NASA
        apiKey: none
        baseUrl: https://power.larc.nasa.gov/cgi-bin/v1/DataAccess.py?
        user: anonymous
      externalServer:
        uri: http://localhost:9000/api/v1/nasa
        method: post

    - name: openweather-job
      sleep: 2000
      failedAttemptMax: 5
      apiProvider:
        name: OPEN_WEATHER_MAP
        apiKey: b6907d289e10d714a6e88b30761fae22
        baseUrl: https://samples.openweathermap.org/data/2.5/weather?
        user: anonymous
      externalServer:
        uri: http://localhost:9000/api/v1/openweather
        method: post

